services:
  mm3_sync:
    image: joergmschulz/mailman3_ldap_sync:latest
    build: 
      context: https://github.com/joergmschulz/mailman3_ldap_sync.git
    container_name: mm3_sync
    hostname: mm3_sync
    volumes:
      - ./config.ini:/etc/mm3sync.ini:ro
      - /data/${DOMAIN}/mm3sync/log/mailman3_ldapsync.log:/var/log/mailman3_ldapsync.log
    environment:
      - DEBUG_DEVELOP=false
      - MM3_MAILMAN_REST_PASSWORD=${MM3_MAILMAN_REST_PASSWORD}
      - MM3SYNC_GROUP_FILTER=${MM3SYNC_GROUP_FILTER}
      - MM3SYNC_SEARCHBASE=${MM3SYNC_SEARCHBASE}
      - MM3SYNC_USER_FILTER=${MM3SYNC_USER_FILTER}
      - MM3API_VERSION=${MM3API_VERSION:-3.1}
      - DOMAIN=${DOMAIN}
      - LDAP_USER=${LDAP_USER}
      - LDAP_PASSWORD=${LDAP_PASSWORD}
      - LDAP_HOSTNAME=${LDAP_HOSTNAME}
      - MM3SYNC_PREFERRED_LANGUAGE=${MM3SYNC_PREFERRED_LANGUAGE:-de}
      - MM3SYNC_DELETE_REST_LIST=${MM3SYNC_DELETE_REST_LIST:-false} 
      - MM3SYNC_DONT_DELETE=${MM3SYNC_DONT_DELETE}
    networks:
      services:
        ipv4_address: ${MM3SYNC_IP}






networks:
  services: 
    external: true
